meta_data:
  script_path: run_scripts/dqn_exp_script.py
  exp_name: dqn_highway_merge
  description: Train an agent using DQN
  num_workers: 1
  using_gpus: true

# -----------------------------------------------------------------------------
variables:
  seed: [0]

# -----------------------------------------------------------------------------
constants:
  net_size: 256
  num_hidden_layers: 2
  share_policy: False
  use_prefix_dict: True

  rl_alg_params:
    num_epochs: 100
    num_steps_per_epoch: 10000
    num_steps_between_train_calls: 10
    num_train_steps_per_train_call: 1
    num_steps_per_eval: 1000
    max_path_length: 100
    min_steps_before_training: 2000

    eval_deterministic: true

    batch_size: 256
    replay_buffer_size: 50000
    no_terminal: false
    wrap_absorbing: false

    save_best: false
    freq_saving: 10
    save_replay_buffer: false
    save_environment: false
    save_algorithm: false

  dqn_params:
    reward_scale: 1.0
    discount: 0.95
    soft_target_tau: 0.005
    qf_lr: 0.0003
    epsilon: 0.2

  env_specs:
    env_creator: "highway"
    env_name: "merge-v2"
    env_kwargs: {}
    training_env_num: 5
    eval_env_num: 5
    training_env_seed: 0
    eval_env_seed: 1
